### ISSUE TITLE
show-apps button (Show Applications) do not fit (style wise) with all themes

### ISSUE THREAD

**Issue by hlechner** [home-sweet-gnome/dash-to-panel#1118]
The Show Applications button displays a bright color on the background of the `overview-icon`, so, on gnome shell themes where the whole button is stylized it look a bit strange:
![image](https://user-images.githubusercontent.com/11244067/89228168-75c71680-d5b5-11ea-88fe-1e0bea739e43.png)

it's on the css file:
```css
.dashtopanelMainPanel .show-apps:hover .overview-icon,
#dashtopanelScrollview .app-well-app:hover .dtp-container,
#dashtopanelScrollview .app-well-app:focus .dtp-container {
	background-color: rgba(238, 238, 236, 0.1);
}
```
Without this style the button look like this (without the overview-icon background):
![image](https://user-images.githubusercontent.com/11244067/89228651-6a281f80-d5b6-11ea-89ef-79dfc96b7d9c.png)

Not sure how could I try to implement something without an option settings or removing the css entry, any ideias?

Thanks!
