### ISSUE TITLE
Panel on the left not fully extending with custom GNOME Shell font size

### ISSUE THREAD

**Issue by lepa22** [home-sweet-gnome/dash-to-panel#1205]
**Describe the bug**
I have set the panel on the left of my primary monitor in order to use it as a Dash to Dock replacement. So I use it with the *Keep original gnome-shell panel* option enabled. I have enabled the User Themes extension and changed the GNOME Shell font size using a custom theme located in `/home/user/.themes/Adwaita_smaller_fonts/gnome-shell/gnome-shell.css` and . Here are the `gnome-shell.css` contents:

```css
/*@import url("/usr/share/gnome-shell/theme/Adwaita/gnome-shell.css");*/

.name-label {
    font-family: "Ubuntu";
    font-size: 10pt;
}

stage {
    font-family: "Ubuntu";
    font-size: 10pt;
    /* color: #5c616b; */
}
```

With this GNOME Shell theme enabled and after restarting GNOME Shell, the left panel does not extend all the way to the bottom of the screen, as seen in the attached screenshot. When I use the default GNOME Shell theme the left panel is fine. The issue is probably that the top panel's size is hard-coded.
 
**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
GNOME Shell 3.36.4

**Dash-to-Panel version**
39

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
Left: custom theme with smaller fonts / Right: default theme

![d2p-bug](https://user-images.githubusercontent.com/16370046/95178173-c5011180-07c7-11eb-9f91-1830f18c4014.png)
