### ISSUE TITLE
Dash-to-Panel blinks when firefox/web browser is maximized and mouse is moving on the panel

### ISSUE THREAD

**Issue by pyway** [home-sweet-gnome/dash-to-panel#1764]
Dash-to-Panel blinks when firefox/web browser is maximized and mouse is moving on the panel icons.

Ubuntu 22.04.
GNOME Shell 42.4

Dash-to-Panel 52 ( occurs with the old versions)
installed directly from github.

**Comment by jonas-w** [comment]
Having the same problem in firefox with intellihide, when i want to open the panel it flickers and is really unusable, this also happens with chromium / chromium based stuff like electron apps (spotify, vscode etc.)

**Comment by pyway** [comment]
I think this problem caused by OS repeatedly updating the area occupied by dash-to-panel.  if dash-to-panel appears as the popup window of an application ( JS related ),  Gnome GUI system will only update the popup window; otherwise, dash-to-panel should be the most top application window, GUI system only updates it, instead of updating two applications alternately.
I also use dash-to-panel with intellihide enabled. thanks to jonas-w.

**Comment by charlesg99** [comment]
Could you define "flickers"? Even better, post a video of it. I've never been able to reproduce a "flicker" with maximized firefox/chromium, xorg or wayland, intellihide or not.

In the linked issue by @m1027, I'm pretty sure "flicker" refers to the fact that the panel is always visible when the extension is first enabled, then after a user defined delay (minimum 10 milliseconds), the panel hides. So you end up always seing the panel's hiding animation, even if you unlock your screen and had a maximized window opened before locking.

**Comment by jonas-w** [comment]
Okay i tried to screenrecord it, but on the screenrecord it looks like it's working. But it differs completely from what i'm really seeing. That's why i'm sending you a video recorded on my phone. And the file is bigger than the upload limit on GitHub so here is the link: https://0x0.st/ovjt.mp4

**Comment by pyway** [comment]
I just installed dash-to-panel, GPaste, GSConnect, no other extensions. but it 's normal with maximized Codium.

**Comment by charlesg99** [comment]
@jonas-w Thanks for the video, I've seen reports of this issue come up from time to time but never was able to reproduce (but I'd love to). I tried to setup my panel as yours but it still behaved normally on my system (gnome-shell 42.5, xorg and wayland). Could you share your dash to panel settings?

@pyway what do you mean by "it's normal", does it work correctly or not?

**Comment by pyway** [comment]
@charlesg99 it's normal that means dash-to-panel works correctly. i recorded a video by my mobile, but i don't know how to share to you.

**Comment by jonas-w** [comment]
@charlesg99 okay the only other notable things i have installed is the Orchis Theme (i already disabled it and it didn't change anything), gsconnect and appindicator support. All the other stuff i have installed shouldn't interfere with it in any way (firefox, rnote, etc.). 

I use plain arch linux with the normal x86_64 kernel and i installed dash-to-panel from the AUR.

It is a fairly new install (3 weeks ago), and it behaves like this since day one.

```toml
[/]
animate-appicon-hover=true
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
appicon-margin=8
appicon-padding=4
available-monitors=[0, 1]
group-apps=true
hotkeys-overlay-combo='TEMPORARILY'
intellihide=true
intellihide-behaviour='ALL_WINDOWS'
intellihide-hide-from-windows=true
intellihide-key-toggle=['<Super>i']
intellihide-key-toggle-text='<Super>i'
intellihide-pressure-threshold=200
intellihide-pressure-time=1500
intellihide-show-in-fullscreen=true
intellihide-use-pressure=true
leftbox-padding=-1
panel-anchors='{"0":"MIDDLE","1":"MIDDLE","2":"MIDDLE"}'
panel-element-positions='{"0":[{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":true,"position":"stackedBR"}],"1":[{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":true,"position":"stackedBR"}]}'
panel-lengths='{"0":70,"1":70,"2":80}'
panel-positions='{"0":"BOTTOM"}'
panel-sizes='{"0":55,"1":55,"2":60}'
primary-monitor=0
show-appmenu=false
status-icon-padding=-1
stockgs-keep-dash=false
stockgs-keep-top-panel=false
stockgs-panelbtn-click-only=false
trans-use-custom-opacity=false
tray-padding=-1
window-preview-title-position='TOP'
```
