### ISSUE TITLE
Edit corner radius of components

### ISSUE THREAD

**Issue by decipher3114** [home-sweet-gnome/dash-to-panel#1819]
**Describe the idea or feature you'd like**
Add option to customize the corner radius for all components like opened apps highlight, date and time, and quick settings button

**Is your feature request related to a problem? Please describe.**
It looks very unconsistent, the date-time, quick settings have a too much roundedness and the apps don't have a liitle bit

**Additional context**
Too much radius, bad padding
![image](https://user-images.githubusercontent.com/84389932/210565457-666e3d9e-854a-42d2-acd0-e29ab6fb9f88.png)
no radius
![image](https://user-images.githubusercontent.com/84389932/210565491-99558b0d-fa53-435b-bf38-3ee919ece38f.png)

**Comment by CoderRuq** [comment]
+1, I know this is incredibly minor but inconsistency like this drives me nuts.

**Comment by LordKordus** [comment]
Yes please make this an option. It feels more 2023.
![Snímek obrazovky z 2023-04-24 13-06-10](https://user-images.githubusercontent.com/105948237/233979844-cbdd3d8e-7b88-44c8-85f9-614a3dace979.png)

**Comment by mon-jai** [comment]
@ghost Can you share you configurations?

That looks really good.

**Comment by ParaSpl01t** [comment]
I know this feature may not be the most important feature but it will add some much needed consistancy.

![Frame 1](https://github.com/home-sweet-gnome/dash-to-panel/assets/18276917/57b86ab7-6449-4043-af09-06d0bf5ba8bc)

**Comment by adem-labsi** [comment]
Hey everyone

After a lot of trial and error, I finally got something like this:

![Screenshot from 2024-06-19 22-39-26](https://github.com/home-sweet-gnome/dash-to-panel/assets/139799064/e2e970e1-50aa-4905-859f-768ecdb6a40f)

I added suggestions from @ghost and @lorduskordus with some tweaks:

![Screenshot from 2024-06-19 22-43-15](https://github.com/home-sweet-gnome/dash-to-panel/assets/139799064/00a4eed3-0dcc-46f4-aec2-01d60cfabb9f)

![1](https://github.com/home-sweet-gnome/dash-to-panel/assets/139799064/28743ad8-0c38-4d4c-a9a1-8733cc6ab76e)

And this is how I made the panel float:

![3](https://github.com/home-sweet-gnome/dash-to-panel/assets/139799064/0c850e72-64eb-48b1-8da7-613c2aaffa1f)

I also enabled **Panel Intellihide** and got rid of the mouse detection from the **panel.js** file.

**Comment by adem-labsi** [comment]
Hey everyone,

After a lot of trial and error, I finally got something like this:

![4](https://github.com/home-sweet-gnome/dash-to-panel/assets/139799064/352c3fac-e117-480a-87a3-a3cf58681ef7)

I added suggestions from @ghost and @lorduskordus with some tweaks:

```css

#dashtopanelScrollview .app-well-app:hover .dtp-container,
#dashtopanelScrollview .app-well-app:focus .dtp-container,
#dashtopanelScrollview .app-well-app .dtp-container > * {
	border-radius: 8px;
}

#dashtopanelScrollview .dash-item-container > StWidget { 
	border-top: 6px;
	border-bottom: 6px;
}

#panel{
	border-radius: 8px;
	border: 3px solid #FFB86C;
}
```

And this is how I made the panel float:

_panel.js_
```js
            x = this.monitor.x;
            y = this.monitor.y + this.monitor.height - this.dtpSize - tbPadding - 6;
```

I also enabled **Panel Intellihide** and got rid of the mouse detection from the **panel.js** file.

**Comment by iFrozenPhoenix** [comment]
Hey guys, I've added
```css
#panel {
    border-radius: 20px;
}
```
to the stylesheet.css.

But with this setting I have stability issues, can't explain why.
I directly modified it in the installed extension.
I've never developed or modified a gnome extension, so I'm completely new to this. 
Do you have an idea what could cause this? Is there maybe a hashsum or something?

**Comment by ParaSpl01t** [comment]
> Hey guys, I've added
> 
> ```css
> #panel {
>     border-radius: 20px;
> }
> ```
> 
> to the stylesheet.css.
> 
> While it leads to the desired visual output, this setting leads to stability issues (When going to locked mode it logs out and disable all extensions), can't explain why. I directly modified it in the installed extension. I've never developed or modified a gnome extension, so I'm completely new to this. Do you have an idea what could cause this? Is there maybe a hashsum or something? Would really appreciate any hint. Thank you in advance.

I'm using this currently, do not know if it leads to any glitch but working good so far.
```css
#dashtopanelScrollview,#dashtopanelScrollview * {
  transition: all 1s ease-in-out;
  }
#dashtopanelScrollview StWidget {
  border-radius: 4px;
}
#dashtopanelScrollview .dash-item-container > StWidget { 
  border-top: 4px;
  border-bottom: 4px;
}
```
