### ISSUE TITLE
Option to add top border

### ISSUE THREAD

**Issue by natewind** [home-sweet-gnome/dash-to-panel#2000]
It would be nice if you could add a border to the panel to better visually separate it from the desktop / app grid when using Blur My Shell. Ideally, just a line with different opacity, like in Windows 11:

![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/30814650/7528ddd9-43cf-4b70-bb74-7a3bf6f668db)

**Comment by natewind** [comment]
A temporary solution fot the impatient:

```css
#panel { border-top: 1px solid rgba(255, 255, 255, 0.2); }
```
