### ISSUE TITLE
panel item not respecting panel border in Gnome 3.32

### ISSUE THREAD

**Issue by Austaras** [home-sweet-gnome/dash-to-panel#600]
when using a theme with following css
``` css
#panel {
	border: 4px solid #000;
	font-weight: light;
	border-top-width: 0;
	border-left-width: 0;
	border-right-width: 0;
}
```
panel items will have same height as whole panel but not height - border width
