### ISSUE TITLE
Update overrides theme panel style (Flat-Remix)

### ISSUE THREAD

**Issue by daniruiz** [home-sweet-gnome/dash-to-panel#633]
Hi! First of all I want to say I love this extension, I've been using it for a while and I can tell for sure you are doing a great job :ok_hand:

My problem here is that I develop this theme https://github.com/daniruiz/flat-remix-gnome which adds a small margin to the panel. As you can see in the screenshot below it worked perfectly until I updated this extension. My main issue is that the background color is applied to  `#panelBox` instead of `#panel` so my theme's margin is applied but cannot be seen.

![image](https://user-images.githubusercontent.com/12565871/57014215-7d0faf80-6c0f-11e9-9bc8-87c689ee75b3.png)

```css
#panelBox {
  padding: 0, .35em .8em;
  background: transparent; /* overridden by the extension */
}

#panel {
  border-radius: 0, 6px;
  background: rgba(0, 0, 0, .2); /* overridden by the extension */
  ...
}
```

My workaround now is to set (from the extension style settings) panel background opacity to 0 and override panel theme gradient opacity to 20% both:

![image](https://user-images.githubusercontent.com/12565871/57014703-813ccc80-6c11-11e9-8b72-de1ed6952c98.png)
