### ISSUE TITLE
wired effect when panelBox has border

### ISSUE THREAD

**Issue by Austaras** [home-sweet-gnome/dash-to-panel#823]
I'm currently using following style
``` css
#panelBox {
  border: 4px solid #505050;
  border-top-width: 0;
  border-left-width: 0;
  border-right-width: 0;
}
```
and recently top panel will have border on both top and bottom
![image](https://user-images.githubusercontent.com/15013925/69392005-7d88a880-0d0f-11ea-9cc0-cff0bbed6c8d.png)

**Comment by charlesg99** [comment]
Hi Austaras, could you add a screenshot where we can actually see something please? I have no idea of what I'm looking at here :P Thanks!

**Comment by Austaras** [comment]
with following css
``` css
#panelBox {
  border: 4px solid red;
  border-top-width: 0;
  border-left-width: 0;
  border-right-width: 0;
}
```
![图片](https://user-images.githubusercontent.com/15013925/69486826-f7916c80-0e8a-11ea-81b2-c12e526769f0.png)
without it
![图片](https://user-images.githubusercontent.com/15013925/69486822-e6e0f680-0e8a-11ea-892a-97099d852ff2.png)

you can see there is a top border which shouldn't be there

**Comment by charlesg99** [comment]
This is what I see when applying that style (on 3.34):

![image](https://user-images.githubusercontent.com/33044886/69486984-67b6d880-0e20-11ea-9369-c02803180e6b.png)

Is that the intended result? What theme are you using? Which dash-to-panel and gnome-shell version? Thanks!

**Comment by Austaras** [comment]
https://github.com/Austaras/dotfile/tree/master/Windows-10

dash-to-panel v26, Gnome 3.34

maybe you need a transparent background(for panel) to see that top border, I'm using
``` css
#panel {
	font-weight: normal;
	color: black;
	height: 32px;
	background-color: rgba(255, 255, 255, 0.4);
	/* border: 4px solid dimgray; */
	font-weight: light;
}
```

**Comment by charlesg99** [comment]
My panel is transparent... just that it is over a black background. I tried with the added #panel style you provided and I get the same result. If I remove that line from your #panelBox style: `border-top-width: 0;` then I can see the red top border...

What theme are you using? Is this a custom one? You know that dash-to-panel provides settings for the panel's height and color right? Thanks!

**Comment by Austaras** [comment]
yeah I'm using a modified theme which lays in here
https://github.com/Austaras/dotfile/tree/master/Windows-10
> You know that dash-to-panel provides settings for the panel's height and color right?
I try to change them and it still has a top border

**Comment by Austaras** [comment]
I remove every css rule except `#panelBox` and `#panel` but top border is still there

**Comment by Austaras** [comment]
also when I set panel to bottom the bottom border went to top of screen
![image](https://user-images.githubusercontent.com/15013925/69516726-7969be80-0f8d-11ea-8194-de564615d322.png)

**Comment by charlesg99** [comment]
Sorry my bad I didn't try hard enough... You're right, I don't see the issue because this was fixed by a recent commit on the master branch. Could you please [install it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) to resolve the issue? Thanks!

**Comment by Austaras** [comment]
Everything works fine in master branch. Thanks for your great work!

**Comment by ferdnyc** [comment]
I know the issue is sorted out, but I just wanted to note that if your intent is to add a red border on the bottom of an element only, instead of doing this:
```css
#panelBox {
  border: 4px solid red;
  border-top-width: 0;
  border-left-width: 0;
  border-right-width: 0;
}
```
You _could_ just do this:
```css
#panelBox {
  border-bottom: 4px solid red;
}
```
